### PR TITLE
Updated Crazyegg integration instructions

### PR DESCRIPTION
**Pull request by shravanjoopally**

### CODE REVIEW

**Review by amee-ce — APPROVED** [review]

**Comment by amee-ce** [comment]
@asaschachar we've updated the logo and the instructions, please review.

**Review by asaschachar — APPROVED** [review]
LGTM!

**Comment by asaschachar** [comment]
Your integration is now live on https://www.optimizely.com/labs/ !

Thanks for your contributions!

**Comment by amee-ce** [comment]
@asaschachar how do we now get it to show up within Optimizely under Settings, Integrations. Like Adobe and Clicktale: https://www.dropbox.com/s/5ysxe1ijw4bjgnk/Screen%20Shot%202021-04-12%20at%202.40.15%20PM.png?dl=0

**Comment by asaschachar** [comment]
Hi @amee-ce, getting your app integrated into the Optimizely Web interface is a separate process. Here is some of the documentation around that process: https://docs.developers.optimizely.com/web/docs/technology-partners

I can also put you in touch with someone on the Optimizely over email so you can get help with this process.

**Pull request merged**
